
name: Pipeline for book-management application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    name: Build and Deploy the application
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
      
    - name: Setting up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    
